- name: Ensure python-apt is installed
  ansible.builtin.apt:
    name: python3-apt
    state: present

- name: Gather package facts
  ansible.builtin.package_facts:
    manager: apt

- name: Ensure R-core deps are installed (2)
  when: 'item not in ansible_facts.packages'
  ansible.builtin.apt:
    name: '{{ item }}'
    state: present
    update_cache: true
  loop:
    - g++
    - gdebi
    - gdebi-core
    - gfortran
    - libblas-dev
    - libbz2-dev
    - libicu-dev
    - liblapack-dev
    - liblzma-dev
    - libopenblas-dev
    - libpaper-utils
    - libpcre2-dev
    - libpcre3-dev
    - libtcl8.6
    - libtk8.6
    - libxt6
    - unzip
    - zip
    - zlib1g-dev

- name: Check if /opt/R is empty
  ansible.builtin.find:
    paths: /opt/R
    file_type: directory
    patterns: "[0-9]\\.[0-9]\\.[0-9]"
  register: any_r_installed

- name: Install R via binary
  when: r_interpreter_install_binary | bool
  block:
    - name: List all installed R versions
      when: r_remove_unused_r_versions | bool and any_r_installed.matched | int != 0
      changed_when: false
      ansible.builtin.shell: ls -d /opt/R/*/ | xargs -n 1 basename
      register: r_installed_list

    - name: Set variable r_installed_list if no R versions are installed
      when: r_remove_unused_r_versions | bool and not any_r_installed.matched
      ansible.builtin.set_fact:
        r_installed_list: { stdout_lines: [] }

    - name: Create diff between lists
      when: any_r_installed.matched | int != 0
      ansible.builtin.set_fact:
        unwanted_r_versions: '{{ r_installed_list.stdout_lines | difference(r_versions) }}'

    - name: Remove deprecated/old R versions
      when: r_remove_unused_r_versions | bool and any_r_installed.matched | int != 0
      ansible.builtin.file:
        path: '/opt/R/{{ item }}'
        state: absent
      loop: '{{ unwanted_r_versions }}'

    - name: Set OS identifier for download
      ansible.builtin.set_fact:
        os_identifier: "{{ '2404' if ansible_facts['distribution_version'] == '24.04' else '2204' if ansible_facts['distribution_version'] == '22.04' else '2004' if ansible_facts['distribution_version'] == '20.04' }}"

    - name: Download R binary (arm64)
      when: ansible_facts['architecture'] == 'aarch64' and not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
      ansible.builtin.get_url:
        url: 'https://fsn1.your-objectstorage.com/devxy-r-builds/{{ os_identifier }}/r-{{ item }}_1_arm64.deb'
        dest: '/tmp/R-{{ item }}.deb'
        force: true
        mode: '0644'
      loop: '{{ r_interpreter_versions }}'

    - name: Download R binary
      when: ansible_facts['architecture'] == 'x86_64' and not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
      ansible.builtin.get_url:
        url: 'https://cdn.posit.co/r/ubuntu-{{ os_identifier }}/pkgs/r-{{ item }}_1_amd64.deb'
        dest: '/tmp/R-{{ item }}.deb'
        mode: '0644'
      loop: '{{ r_interpreter_versions }}'

    # without it, the deb package might be broken if someone manually removed /opt/r-<version>
    - name: Uninstall existing R binaries
      when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
      ansible.builtin.apt:
        name: 'r-{{ item }}'
        state: absent
      loop: '{{ r_interpreter_versions }}'

    - name: Install R binary
      when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
      ansible.builtin.apt:
        deb: '/tmp/R-{{ item }}.deb'
        force: true
        state: present
      loop: '{{ r_interpreter_versions }}'

    - name: Cleanup downloaded assets
      when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
      ansible.builtin.file:
        path: '/tmp/R-{{ item }}.deb'
        state: absent
      loop: '{{ r_interpreter_versions }}'

- name: Install R from tarball
  when: not r_interpreter_install_binary | bool
  block:
    - name: Message
      ansible.builtin.debug:
        msg: 'Installing R from source using local tarballs in {{ r_interpreter_source_path }}'
    - name: List all installed R versions (source)
      ansible.builtin.shell: ls /opt/R | grep "[0-9]\\.[0-9]\\.[0-9]"
      register: r_installed_list

    - name: Set variable r_installed_list if no R versions are installed (source)
      when: r_remove_unused_r_versions | bool and not any_r_installed.matched
      ansible.builtin.set_fact:
        r_installed_list: { stdout_lines: [] }

    - name: Create diff between lists (source)
      when: any_r_installed.matched | int != 0
      ansible.builtin.set_fact:
        unwanted_r_versions: '{{ r_installed_list.stdout_lines | difference(r_versions) }}'

    - name: Ensure required system dependencies are installed (source)
      when: 'item not in ansible_facts.packages'
      ansible.builtin.apt:
        name: '{{ item }}'
        state: present
      loop:
        - curl
        - make
        - tar
        - libcurl4-openssl-dev
        - libicu-dev
        - libopenblas-dev
        - libpcre2-dev
        - wget
        - python3-pip
        - libreadline-dev

    - name: Install R binary (source)
      when: not (item in r_installed.results | selectattr('stat.exists') | map(attribute='item') | list)
      ansible.builtin.shell: |
        set -xe
        cd "{{ r_interpreter_source_path }}"
        mkdir -p "/opt/R/{{ item }}"
        tar -xzf "R-{{ item }}.tar.gz"
        cd "R-{{ item }}"
        ./configure --prefix="/opt/R/{{ item }}" --enable-R-shlib --with-tcltk --enable-memory-profiling --with-x --with-blas --with-lapack
        make -j 4 -O
        make install
        cd ..
        rm -rf "R-{{ item }}"
      loop: '{{ r_interpreter_versions }}'

- name: Configure /etc/Rprofile.site (default, Ubuntu)
  when: r_custom_repos is undefined
  ansible.builtin.blockinfile:
    create: true
    path: /etc/Rprofile.site
    mode: '0644'
    block: |
      # devxy.data_science_core.r
      options(install.packages.check.source = 'no',
        repos = structure(c(CRAN = "https://p3m.dev/cran/__linux__/{{ ansible_facts['distribution_release'] }}/latest")))
