collections:
  - name: community.general
    version: 11.4.1

roles:
  - name: nginxinc.nginx
    version: 0.25.0
  - name: nginxinc.nginx_config
    version: 0.7.1
  - src: https://codefloe.com/devxy/ansible-certbot.git
    scm: git
    version: 5.4.1
    name: devxy.certbot
