- name: "'Remove mode': Calculate difference between installed and wanted Python versions"
  when: python_remove_unused_python_versions | bool
  ansible.builtin.set_fact:
    difference: >-
      {{
        python_versions_installed_list | map(attribute='version') | list
        | difference(python_interpreter_versions)
      }}

- name: "'Remove mode': Print difference between installed and wanted Python versions"
  ansible.builtin.debug:
    msg: '{{ difference }}'

- name: "'Remove mode': Find paths for versions to be removed"
  when: difference | length > 0 and python_remove_unused_python_versions | bool
  ansible.builtin.set_fact:
    paths_to_remove: >-
      {{
        python_versions_installed_list | selectattr('version', 'in', difference) | map(attribute='path') | list
      }}

- name: "'Remove mode': Remove unwanted Python versions"
  when: difference | length > 0 and python_remove_unused_python_versions | bool
  ansible.builtin.file:
    path: '{{ item }}'
    state: absent
  loop: '{{ paths_to_remove }}'
