- name: Verify
  hosts: all
  become: false
  gather_facts: true

  tasks:
    - name: Gather package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Define expected packages (RedHat)
      when: ansible_facts['os_family'] == 'RedHat'
      ansible.builtin.set_fact:
        expected_packages:
          - libgit2
          - libxml2
          - cairo
          - git

    - name: Define expected packages (Ubuntu)
      when: ansible_facts['distribution'] == 'Ubuntu'
      ansible.builtin.set_fact:
        expected_packages:
          - libgit2-dev
          - libxml2-dev
          - libcairo2-dev
          - git

    - name: Assert key packages are installed
      ansible.builtin.assert:
        that:
          - item in ansible_facts.packages
        msg: 'Expected package {{ item }} is not installed'
      loop: '{{ expected_packages }}'
