# defaults file for python

# this always installs the latest version of the respective minor
# string notation is important as otherwise trailing zeros are cut
# @var python_interpreter_versions:type: list
python_interpreter_versions:
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'

# @var python_update_versions:description: If true, automatically updates the minor versions in `python_interpreter_versions` to the latest patch version
# @var python_update_versions:type: boolean
python_update_versions: true

# @var python_remove_unused_python_versions:description: Whether to remove python versions not listed in `python_interpreter_versions`
# @var python_remove_unused_python_versions:type: boolean
python_remove_unused_python_versions: true
