galaxy_info:
  author: Patrick Schratz
  description: ''
  company: devXY GmbH
  issue_tracker_url: https://git.devxy.io/ansible/ansible-ds-core/issues

  license: AGPL-3.0-or-later

  min_ansible_version: '2.9'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - r
    - datascience

dependencies: []
