galaxy_info:
  author: Patrick Schratz
  description: 'Installs R <https://cran.r-project.org/>'
  company: devXY GmbH
  issue_tracker_url: https://codefloe.com/devxy/data_science_core/issues

  license: AGPL-3.0-or-later

  min_ansible_version: '2.9'

  platforms:
    - name: EL
      versions:
        - '8'
        - '9'
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - r
    - datascience

dependencies: []
