when:
  - event: pull_request
    evaluate: 'CI_COMMIT_SOURCE_BRANCH != "next-release/main"'

steps:
  commitlint:
    image: commitlint/commitlint:19.5.0
    commands:
      - echo $${CI_COMMIT_MESSAGE} | commitlint
