when:
  - event: push
    branch: ${CI_REPO_DEFAULT_BRANCH}
  - event: manual
    evaluate: 'TASK == "release-helper"'

steps:
  release-helper:
    image: docker.io/woodpeckerci/plugin-ready-release-go:2.0.0
    settings:
      git_email: mail@devxy.io
      forge_token:
        from_secret: renovate_token
    backend_options:
      kubernetes:
        ### PROD-parallel
        resources:
          requests:
            memory: 300Mi
            cpu: 100m
          limits:
            memory: 500Mi
            cpu: 1000m
